replicaCount: 1

image:
  repository: rupesh1997/backend
  pullPolicy: IfNotPresent
  tag: "1.0.0"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
