kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  labels:
    app: backend
  namespace: kubernetes-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rupesh1997/devops-day-02:{{ .Values.image.tag }}
          ports:
            - containerPort: 8282
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 10
