apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kubernetes-live
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rupesh1997/devops-day-02:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 10
